# traducao do README

pfile = /var/www/preserv.addressforall.org/download

lotes: lotes_paso1 lotes_passo2

lotes_passo1:
        unzip -x $(pfile)/fbc62efdbd0f16a7db03b5b775c50c9425367a8dee8a85d9b53e4475bbdb99d2.zip -O /tmp/pg_io
	shp2pgsql ...

lotes_passo2:
